import { execFile } from "node:child_process";
import {
  cp,
  mkdir,
  mkdtemp,
  readFile,
  readdir,
  rm,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { fromMarkdown } from "../../markdown/src/index.ts";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { createLatexPackage as createPackage } from "../src/package.ts";
import { template } from "../../template-ieee/src/index.ts";
const createLatexPackage: typeof createPackage = (document, options) =>
  createPackage(document, { template, ...options });
import { compileLatexPackage, writeLatexPackage } from "../src/node.ts";

const execute = promisify(execFile);
const articles = fileURLToPath(
  new URL("../../../examples/articles/", import.meta.url),
);
const bin = fileURLToPath(new URL("../../cli/src/bin.ts", import.meta.url));
const artifacts = process.env["PUBLISLE_RESEARCH_ARTIFACTS"];
let directory: string;
let journal: string;
let unicode: string;

beforeAll(async () => {
  if (artifacts) await mkdir(artifacts, { recursive: true });
  directory = await mkdtemp(
    join(artifacts ?? tmpdir(), "publisle-research-test-"),
  );
  journal = join(directory, "ieee-journal");
  unicode = join(directory, "ieee-unicode");
  for (const [name, engine, output] of [
    ["ieee-journal", "pdflatex", journal],
    ["ieee-unicode", "lualatex", unicode],
  ] as const) {
    await execute(
      process.execPath,
      [
        bin,
        "export",
        join(articles, `${name}.md`),
        "--to",
        "submission",
        "--template",
        "ieee-journal",
        "--engine",
        engine,
        "--output",
        output,
      ],
      { timeout: 180_000, maxBuffer: 4 * 1024 * 1024 },
    );
  }
});
afterAll(async () => {
  if (!artifacts) await rm(directory, { recursive: true, force: true });
});

async function extract(output: string) {
  return (
    await execute("pdftotext", ["-layout", join(output, "manuscript.pdf"), "-"])
  ).stdout;
}
async function source() {
  const result = fromMarkdown(
    await readFile(join(articles, "ieee-journal.md"), "utf8"),
  );
  if (!result.document) throw new Error("Fixture did not parse");
  return createLatexPackage(result.document);
}

describe("local IEEE journal exports", () => {
  it("exports a multi-page Letter manuscript with embedded non-Type-3 fonts and resolved objects", async () => {
    const info = (await execute("pdfinfo", [join(journal, "manuscript.pdf")]))
      .stdout;
    expect(info).toMatch(/Pages:\s+[2-9]/u);
    expect(info).toMatch(/Page size:\s+612 x 792 pts/u);
    const text = await extract(journal);
    for (const content of [
      "Ada Example",
      "Abstract",
      "Index Terms",
      "Equation 1",
      "Section III",
      "Figure 1",
      "Table I",
      "0.013504",
      "C. E. Shannon",
    ])
      expect(text).toContain(content);
    const fonts = (await execute("pdffonts", [join(journal, "manuscript.pdf")]))
      .stdout;
    expect(fonts).not.toContain("Type 3");
    for (const row of fonts.trim().split("\n").slice(2))
      expect(row).toMatch(/\s+yes\s+yes\s+yes\s+/u);
    const manifest = JSON.parse(
      await readFile(join(journal, "manifest.json"), "utf8"),
    ) as { diagnostics: { code: string }[] };
    expect(manifest.diagnostics.map((loss) => loss.code)).toEqual([
      "pdf-ua-unavailable",
    ]);
    const bbl = await readFile(join(journal, "manuscript.bbl"), "utf8");
    expect(bbl).toContain("Generated by IEEEtran.bst");
    expect(bbl).toContain("\\bibitem{shannon1949}");
  });

  it("renders Arabic, Chinese and math without replacement glyphs", async () => {
    const text = (await extract(unicode)).normalize("NFKC");
    expect(text).toContain("مرحبا بالعالم");
    expect(text).toContain("中文研究论文测试");
    expect(text).toContain("≤");
    expect(text).not.toContain("�");
    const fonts = (await execute("pdffonts", [join(unicode, "manuscript.pdf")]))
      .stdout;
    expect(fonts).toContain("PakTypeNaskhBasic");
    expect(fonts).toContain("FandolSong");
    const log = await readFile(join(unicode, "manuscript.log"), "utf8");
    expect(log).not.toMatch(
      /Missing character:|undefined references|Overfull \\[hv]box/u,
    );
    await execute("pdftoppm", [
      "-f",
      "1",
      "-singlefile",
      "-scale-to",
      "1500",
      "-png",
      join(unicode, "manuscript.pdf"),
      join(unicode, "page-1"),
    ]);
  });

  it("rebuilds both packages using only exported sources and assets in fresh directories", async () => {
    for (const [output, flag] of [
      [journal, "-pdf"],
      [unicode, "-lualatex"],
    ] as const) {
      const rebuild = await mkdtemp(join(directory, "rebuild-"));
      for (const name of ["manuscript.tex", "references.bib"])
        await cp(join(output, name), join(rebuild, name));
      if ((await readdir(output)).includes("assets"))
        await cp(join(output, "assets"), join(rebuild, "assets"), {
          recursive: true,
        });
      await execute(
        "latexmk",
        [
          flag,
          "-norc",
          "-interaction=nonstopmode",
          "-halt-on-error",
          "-no-shell-escape",
          "manuscript.tex",
        ],
        { cwd: rebuild, timeout: 120_000, maxBuffer: 4 * 1024 * 1024 },
      );
      expect(await extract(rebuild)).toBe(await extract(output));
    }
    for (const page of [1, 2])
      await execute("pdftoppm", [
        "-f",
        String(page),
        "-singlefile",
        "-scale-to",
        "1500",
        "-png",
        join(journal, "manuscript.pdf"),
        join(journal, `page-${String(page)}`),
      ]);
  });

  it("exports PDF directly and refuses existing outputs without changing them", async () => {
    const output = join(directory, "direct.pdf");
    await execute(
      process.execPath,
      [
        bin,
        "export",
        join(articles, "ieee-journal.md"),
        "--to",
        "pdf",
        "--template",
        "ieee-journal",
        "--output",
        output,
      ],
      { timeout: 120_000 },
    );
    const original = await readFile(output);
    await expect(
      execute(process.execPath, [
        bin,
        "export",
        join(articles, "ieee-journal.md"),
        "--to",
        "pdf",
        "--template",
        "ieee-journal",
        "--output",
        output,
      ]),
    ).rejects.toMatchObject({ code: 2 });
    expect(await readFile(output)).toEqual(original);
    await expect(
      execute(process.execPath, [
        bin,
        "export",
        join(articles, "ieee-journal.md"),
        "--to",
        "submission",
        "--template",
        "ieee-journal",
        "--output",
        journal,
      ]),
    ).rejects.toMatchObject({ code: 2 });
    expect(await readdir(journal)).toContain("manuscript.pdf");
  });

  it("reports missing assets, missing tools, timeout, missing fonts and missing glyphs", async () => {
    const pkg = await source();
    await expect(
      compileLatexPackage(
        {
          ...pkg,
          assets: [
            { source: "missing.pdf", destination: "assets/missing.pdf" },
          ],
        },
        { sourceDirectory: articles },
      ),
    ).rejects.toThrow(/ENOENT/u);
    await expect(
      compileLatexPackage(
        {
          ...pkg,
          assets: [
            { source: "../consumer/README.md", destination: "outside.pdf" },
          ],
        },
        { sourceDirectory: articles },
      ),
    ).rejects.toThrow(/escapes manuscript directory/u);
    const oldPath = process.env["PATH"];
    try {
      process.env["PATH"] = "";
      await expect(
        compileLatexPackage(pkg, { sourceDirectory: articles }),
      ).rejects.toThrow(/latexmk/u);
    } finally {
      if (oldPath === undefined) delete process.env["PATH"];
      else process.env["PATH"] = oldPath;
    }
    await expect(
      compileLatexPackage(pkg, { sourceDirectory: articles, timeoutMs: 1 }),
    ).rejects.toThrow(/compilation failed|compiler|font/u);
    await expect(
      compileLatexPackage(
        {
          ...pkg,
          assets: [],
          files: {
            ...pkg.files,
            "manuscript.tex":
              "\\documentclass{article}\n\\begin{document}\n\\loop\\iftrue\\repeat\n\\end{document}\n",
          },
        },
        { sourceDirectory: articles, timeoutMs: 500 },
      ),
    ).rejects.toThrow(/timed out/u);
    const parsed = fromMarkdown(
      await readFile(join(articles, "ieee-unicode.md"), "utf8"),
    );
    if (!parsed.document) throw new Error("Fixture did not parse");
    await expect(
      compileLatexPackage(
        createLatexPackage(parsed.document, {
          engine: "lualatex",
          fonts: { arabic: "Publisle Missing Font 12345" },
        }),
        { sourceDirectory: articles },
      ),
    ).rejects.toThrow(/compilation failed|compiler|font/u);
    const missingGlyph = {
      ...pkg,
      engine: "lualatex" as const,
      files: {
        ...pkg.files,
        "manuscript.tex":
          "\\documentclass{article}\n\\begin{document}\n中文\n\\end{document}\n",
      },
    };
    await expect(
      compileLatexPackage(missingGlyph, { sourceDirectory: articles }),
    ).rejects.toThrow(/missing glyphs/u);
  });

  it("keeps failed builds unpublished and protects package paths", async () => {
    const pkg = await source();
    await expect(
      compileLatexPackage(
        { ...pkg, files: { ...pkg.files, "../outside.tex": "bad" } },
        { sourceDirectory: articles },
      ),
    ).rejects.toThrow(/Unsafe package path/u);
    const output = join(directory, "invalid-style");
    await expect(
      execute(process.execPath, [
        bin,
        "export",
        join(articles, "ieee-journal.md"),
        "--to",
        "submission",
        "--template",
        "ieee-journal",
        "--style",
        "author-date",
        "--output",
        output,
      ]),
    ).rejects.toMatchObject({
      code: 2,
      stderr: expect.stringContaining("numeric") as unknown,
    });
    await expect(readFile(join(output, "manuscript.pdf"))).rejects.toThrow(
      /ENOENT/u,
    );
    const claimed = join(directory, "claimed");
    await mkdir(claimed);
    await writeFile(join(claimed, "keep.txt"), "keep");
    await expect(
      writeLatexPackage(
        { pdf: new Uint8Array(), files: { a: "a" }, diagnostics: [] },
        claimed,
      ),
    ).rejects.toThrow(/EEXIST/u);
    expect(await readFile(join(claimed, "keep.txt"), "utf8")).toBe("keep");
  });
});
